version = 3
final_space = true

[transient_prompt]
background = "transparent"
foreground = "lightGreen"
template = "❯ "

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    template = '{{ .UserName }} '
    foreground = 'lightYellow'
    type = 'session'
    style = 'plain'

  [[blocks.segments]]
    template = '<#ffffff>in</> {{ .Path }} '
    foreground = 'cyan'
    type = 'path'
    style = 'plain'

    [blocks.segments.properties]
      style = 'folder'

  [[blocks.segments]]
    template = '<#ffffff>on</> {{ .HEAD }}{{ if gt .StashCount 0 }}  {{ .StashCount }}{{ end }} '
    foreground = '#ff94df'
    type = 'git'
    style = 'plain'

    [blocks.segments.properties]
      branch_icon = ' <#ff94df><b> </b></>'
      fetch_stash_count = true

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    template = '❯'
    foreground = 'lightGreen'
    type = 'text'
    style = 'plain'
